apiVersion: v1
kind: Namespace
metadata:
  name: flux-counter
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: flux-counter
  namespace: flux-counter
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: sikalabs
        namespace: flux-system
      chart: counter
      interval: 1m
  values:
    host: flux-counter.t-mobile.sikademo.com
    EXTRA_TEXT: "T-Mobile"
    FONT_COLOR: "#ffffff"
    BACKGROUND_COLOR: "#e20074"
