apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: hello-world
  namespace: hello-world
spec:
  interval: 1m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: sikalabs
        namespace: flux-system
      chart: hello-world
      version: "0.1.0"
      interval: 1m
  values:
    TEXT: "Hello T-Mobile @ Minikube"
    COLOR: "magena"
